const students = [{
    "id": 1,
    "first_name": "Gracia",
    "last_name": "Mowsley",
    "email": "gmowsley0@ca.gov"
  }, {
    "id": 2,
    "first_name": "Deirdre",
    "last_name": "Fuggle",
    "email": "dfuggle1@ihg.com"
  }, {
    "id": 3,
    "first_name": "Rollin",
    "last_name": "Golagley",
    "email": "rgolagley2@theguardian.com"
  }, {
    "id": 4,
    "first_name": "Inger",
    "last_name": "Bettleson",
    "email": "ibettleson3@newyorker.com"
  }, {
    "id": 5,
    "first_name": "Gabriello",
    "last_name": "Tackley",
    "email": "gtackley4@tuttocitta.it"
  }, {
    "id": 6,
    "first_name": "Nicola",
    "last_name": "Brayshaw",
    "email": "nbrayshaw5@comsenz.com"
  }, {
    "id": 7,
    "first_name": "Ruggiero",
    "last_name": "Rustadge",
    "email": "rrustadge6@timesonline.co.uk"
  }, {
    "id": 8,
    "first_name": "Derick",
    "last_name": "Goede",
    "email": "dgoede7@about.com"
  }, {
    "id": 9,
    "first_name": "Cory",
    "last_name": "Barnson",
    "email": "cbarnson8@pbs.org"
  }, {
    "id": 10,
    "first_name": "Darbee",
    "last_name": "Treadgall",
    "email": "dtreadgall9@bloomberg.com"
  }]
  module.exports = students